services:
  - type: web
    name: fraudshield-dashboard
    env: docker
    dockerfilePath: ./Dockerfile
    dockerTarget: dash
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 8050
